### ISSUE TITLE
Critical error when trying to bind a serial number to an order

### ISSUE THREAD

**Issue by Bappi** [pluginever/wc-serial-numbers#243]
When trying to bind a serial number to an order, a critical error is thrown. 

WordPress version 6.0.2
Active theme: jerungwheels (version 1.1)
Current plugin: WooCommerce Serial Numbers (version 1.2.10)
PHP version 7.4.30

Error Details
=============
An error of type E_ERROR was caused in line 377 of the file /home/rodashark/public_html/assets/plugins/wc-serial-numbers/includes/wc-serial-numbers-functions.php. Error message: Uncaught Error: Call to a member function get_id() on bool in /home/rodashark/public_html/assets/plugins/wc-serial-numbers/includes/wc-serial-numbers-functions.php:377
Stack trace:
#0 /home/rodashark/public_html/assets/plugins/wc-serial-numbers/includes/admin/class-wc-serial-numbers-admin-actions.php(29): wc_serial_numbers_insert_serial_number(Array)
#1 /home/rodashark/public_html/wp-includes/class-wp-hook.php(307): WC_Serial_Numbers_Admin_Actions::edit_serial_number('')
#2 /home/rodashark/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#3 /home/rodashark/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#4 /home/rodashark/public_html/wp-admin/admin-post.php(85): do_action('admin_post_wc_s...')
#5 {main}

**Comment by Bappi** [comment]
Not replicable in 1.3.1
